language: ruby
cache: bundler
rvm:
- 2.3.1
script: bundle exec rake
before_install:
- gem update --system
services:
- redis-server
deploy:
  provider: rubygems
  api_key:
    secure: b3WMkStlgn09VthZit4RpetLVW/mIRL+mC+zVE37kf3jcvSmfRn0wbmdyZ1+71OB0nsYTwKUe4vZOScRfeu1/ME3QeFNLsjfY3JbwpBhihLSSTBmEfcwob4D/qS18GGcUqbjxHcxYydCA3yDxie6pTDsxwhxMzxrFUecyxCYxs94eiyytssm+TlAy/gsN55zudzU44HMpOOxiEuZUFDj1irkGli16/bJCNXMFvOD6R099FYKJ63rZJ2+H0b0YTHvr7p72wwktge5z51lgLNlFcWDjYuUfCRogO8LkmRd3kGyFrj+7RkHU3OWvqg/bESgDqzOsnH0baUQZrdsh9IxlaPdbhvdC9mB79V78E15NhLJ4aAYCiaZpJSOFQCN0pgEmX97YZ0zJVDnOarh1h1HiJM5Cs2vJ2QOD4qf1DlEIRlyxJyOUstZdQv+j7tYpkZOBlHbosbZ+7zTRBiIeCGqeAKTBrKwgJ2qCCwARe6G4WkvRNJSVZ83uvHQ25XJnQlO3io8PZhQhODtOnz0WfHtjY95eL66IYywnWxoUED5tjJlYuEmvRvw2ZeNcUnajaVL1dVVTdd/+nOy7JV4k7kdRRDvI+h0KapjA980BTByueUKV93yHN7c4q7u+ah67CaCGLSwSRU9BE9gdWstgdj97loiEvAJT7clsfijNVqOEYY=
  gem: lita-line
  on:
    repo: aar0nTw/lita-line
addons:
  code_climate:
    repo_token:
      secure: xsmLBjL5tg2SkdbBAEmQ01zd3sASOAOHoiGBdBYYRZF4NNaMrVDNz1Tvi+4Pv0KpCCbg5TALh1ougaZrlg33fEw8DYbQoVLTmzTbZTErXxb5k6kvB/Wjs2rDJ8zWz0CAT3w64xyLm/XmledB7oZa+dzZznW8P6H83Ibw8Qa+nlyPePyB/UoDv6oAKO4b76WjeNz8wSVGawqf0yQas+BbD966B7NnNtogV3AhHiGec/X9HDqJuV2Z6bBCRX/1Hs/YDOaieyoOIn6XU7nLghymTezNEPyk6DttZpRpdBR0n6KgLuhPfcTd6TtyGDnPhnlk/rLg3/tRjKGwHj3PNjJ0ser4VFO0dpmumt60htMAKUQC3tInmuGlI4Uumpo8Ra4IsaU20/jtJKdI75PYRolqyETnR5c+Z++tZOw/l7VskLBdVKow+9ZGrePGFuumEdXG/JsFbVAilgYUubU3opCXvQ20QtlE7iSL/rwZEZEDrx/8yvjmSsqnGF5PdBrrNs4ZUxEizp5KqzyAnLLXQVEI+IDDH3uLKdSrKfiUbK2SNkULJq+eUivwgpnmDybhmjGgTsnZzWwB1NROB0JQgH5Yd+Wb9pIkmmrSu+BTNjQ+Ywo4SQkA+XYS2aP1HrZJGHMqROsZXY3EybqlTFTZ1K0apj/b4Bw7CaNH9FdKhFQBv0w=
